version: '3.8'

services:

  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  user-service:
    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8100:8100"