server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: *
#            allowedMethods: *
#          default-filters:
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: video-service
          uri: http://video-service:8200
          predicates:
            - Path=/video/**
        - id: user-service
          uri: http://user-service:8100
          predicates:
            - Path=/user/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
#       defaultZone: http://localhost:8761/eureka



