spring:
  application:
    name: video-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: videos_db
      host: mongodb2
      port: 27027


server:
  port: 8200

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
#       defaultZone: http://localhost:8761/eureka


