spring:
  application:
    name: user-service

server:
  port: 8100

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka}
#       defaultZone: http://localhost:8761/eureka
